name: nginx-extras
on:
  push:
    branches:
      - master
    pull_request:
env:
  NGINX_VERSION: 1.17.10
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REGISTRY_URL: ${{REGISTRY_URL}}
jobs:
  platform:
    name: nginx-extras
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: build nginx
        run: |
          docker build -t ${{github.workflow}}:${{env.NGINX_VERSION}} --pull --build-arg "NGINX_VERSION=${{env.NGINX_VERSION}}" .
          docker tag ${{github.workflow}}:${{env.NGINX_VERSION}} ${{secrets.REGISTRY_URL}}/${{github.workflow}}:${{env.NGINX_VERSION}}
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} https://${{secrets.REGISTRY_URL}}
          docker push ${{secrets.REGISTRY_URL}}/${{github.workflow}}:${{env.NGINX_VERSION}}
